name: krrng_client
description: krrng flutter project

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # network
  dio:
  platform:
  build_runner:
  package_info:
  json_annotation:
  shared_preferences:
  json_serializable:

  formz: ^0.4.0
  logger: ^1.1.0
  freezed: ^0.14.1
  equatable: ^2.0.3
  intl: ^0.17.0

  # login
  kakao_flutter_sdk: ^1.3.0-beta.4
  sign_in_with_apple: ^3.2.0

  # onesignal
  onesignal_flutter:

  # web
  vrouter: ^1.2.0+21
  url_strategy: ^0.2.0
  universal_html: ^2.0.8
  url_launcher_web: ^2.0.6

  # bloc
  bloc: ^7.2.1
  flutter_bloc: ^7.3.3

  # webview
  flutter_html: ^2.2.1
  webview_flutter: ^2.0.4

  # helpers
  flutter_svg: ^0.23.0
  currency_formatter: ^1.2.1
  permission_handler: ^9.2.0
  wrapped_korean_text: ^0.0.2
  flutter_swiper_plus: ^2.0.4
  flutter_svg_provider: ^0.1.11
  flutter_native_splash: ^1.3.3
  carousel_slider: ^4.1.1
  flutter_sizer: ^1.0.5
  kpostal: ^0.4.2
  flutter_swipe_action_cell: ^3.0.4
  double_back_to_close: ^2.0.0
  cached_network_image: ^3.2.2

  # payment
#  iamport_flutter: ^0.10.3
  flutter_multi_formatter:

  # cupertino_icons
  cupertino_icons: ^1.0.2

  # image
  multi_image_picker: ^4.8.1

  # naver map
  flutter_naver_map:
    git: https://github.com/wnsgh78b/flutter_naver_map.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: NanumSquareRound
      fonts:
        - asset: assets/fonts/NanumSquareRoundL.ttf
          weight: 300
        - asset: assets/fonts/NanumSquareRoundR.ttf
          weight: 500
        - asset: assets/fonts/NanumSquareRoundB.ttf
          weight: 700
        - asset: assets/fonts/NanumSquareRoundEB.ttf
          weight: 900

  assets:
    - assets/
    - assets/icons/
    - assets/images/

flutter_native_splash:

  background_image: assets/images/splash.png
  web_image_mode: cover
  full_screen: true
  android: true
  ios: true
  web: true
